/* ============================================
   Martech Audit Toolkit - Shared JS v2.0
   ============================================ */

/**
 * Copy the content of the <pre><code> block adjacent to the button's header.
 * Falls back to a textarea approach for non-HTTPS contexts.
 */
function copyCode(btn) {
    const code = btn.closest('.code-header').nextElementSibling.textContent;

    if (navigator.clipboard && window.isSecureContext) {
        navigator.clipboard.writeText(code).then(() => showCopied(btn));
    } else {
        // Fallback for non-secure contexts (file://, http://)
        const textarea = document.createElement('textarea');
        textarea.value = code;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        showCopied(btn);
    }
}

function showCopied(btn) {
    const originalText = btn.innerHTML;
    btn.innerHTML = 'Copiado!';
    btn.classList.add('copied');
    setTimeout(() => {
        btn.innerHTML = originalText;
        btn.classList.remove('copied');
    }, 2000);
}

/**
 * Download a JS object as a timestamped JSON file.
 */
function downloadJSON(data, prefix) {
    const hostname = window.location.hostname || 'local';
    const date = new Date().toISOString().slice(0, 10);
    const filename = `${prefix}_${hostname}_${date}.json`;
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    console.log('Downloaded:', filename);
}

/**
 * Generate and download an HTML report from scan results.
 */
function downloadHTMLReport(data, title, prefix) {
    const hostname = window.location.hostname || 'local';
    const date = new Date().toISOString().slice(0, 10);
    const filename = `${prefix}_${hostname}_${date}.html`;

    const sections = Object.entries(data)
        .filter(([, val]) => val && (typeof val === 'object' ? Object.keys(val).length > 0 : val))
        .map(([key, val]) => {
            const content = typeof val === 'object'
                ? `<pre>${JSON.stringify(val, null, 2)}</pre>`
                : `<p>${val}</p>`;
            return `<div class="section"><h3>${key}</h3>${content}</div>`;
        }).join('');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title} - ${hostname}</title>
<style>
body{font-family:system-ui,sans-serif;background:#0a0a0a;color:#e5e5e5;padding:40px 20px;max-width:900px;margin:0 auto}
h1{color:#FF8C42;border-bottom:2px solid #FF8C42;padding-bottom:10px}
h3{color:#FFB088;margin-top:25px}
pre{background:#141414;padding:15px;border-radius:8px;overflow-x:auto;font-size:0.85em;border:1px solid #222}
.meta{color:#808080;font-size:0.9em;margin-bottom:30px}
.section{margin-bottom:20px;padding:15px;background:#141414;border-radius:10px;border:1px solid #222}
</style>
</head>
<body>
<h1>${title}</h1>
<p class="meta">Site: ${hostname} | Date: ${date} | Generated by Martech Audit Toolkit v2.0</p>
${sections}
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    console.log('HTML Report downloaded:', filename);
}
